export const STATUS = {
  TODO: "TO-DO",
  INPROGRESS: "IN-PROGRESS",
  COMPLETED: "COMPLETED",
  INTEST: "IN-TEST",
  CLOSED: "CLOSED",
};

export const COLUMNS = {
  TODO: "TO-DO",
  INPROGRESS: "IN-PROGRESS",
  COMPLETED: "COMPLETED",
  INTEST: "IN-TEST",
  CLOSED: "CLOSED",
};
